- hosts: all
  tasks:
    - name: Add apt keys
      apt_key:
        url: https://repos.insights.digitalocean.com/sonar-agent.asc
    - name: Add apt repositories
      apt_repository:
        repo: deb https://repos.insights.digitalocean.com/apt/do-agent/ main main
    - name: Upgrade apt packages
      apt:
        upgrade: full
        update_cache: yes
    - name: Install apt packages
      apt:
        name:
          - do-agent
          - openjdk-18-jre-headless
          - s3cmd
          - ufw
        state: latest
        update_cache: yes
    - name: Enable firewall
      ufw:
        state: enabled
        rule: allow
        name: OpenSSH
    - name: Get planetiler.jar
      get_url:
        url: https://github.com/onthegomap/planetiler/releases/latest/download/planetiler.jar
        dest: ~/planetiler.jar
    - name: Run script
      script: runworld.sh
    - name: Copy s3cfg
      copy:
        src: ~/.s3cfg
        dest: .s3cfg
    - name: Upload tiles
      shell: s3cmd put --force --acl-public --multipart-chunk-size-mb=5120 planet.mbtiles s3://data.fieldmaps.io/tileserver_gl/data/planet.mbtiles
      register: result
      until: result.rc == 0
    - name: Shutdown machine
      community.general.shutdown:
