- hosts: all
  tasks:
    - name: Sync tiles
      shell: s3cmd sync --delete-removed --exclude planet.mbtiles s3://data.fieldmaps.io/tileserver_gl /mnt/
      register: result
      until: result.rc == 0
    - name: Reboot machine
      reboot:
